#!/bin/sh
# PreToolUse guard — protect generated / build output.
# Blocks Edit/Write into directories that are regenerated by the build so edits there are
# never wasted or misleading. Reads the tool-call JSON on stdin; exit code 2 blocks (stderr = reason).

input=$(cat)

fp=$(printf '%s' "$input" \
  | grep -oE '"file_path"[[:space:]]*:[[:space:]]*"[^"]*"' | head -n1 \
  | sed -E 's/.*:[[:space:]]*"([^"]*)"/\1/')

[ -z "$fp" ] && exit 0

case "$fp" in
  */backend/target/*|backend/target/* \
  |*/frontend/dist/*|frontend/dist/* \
  |*/frontend/node_modules/*|frontend/node_modules/* \
  |*/frontend/.angular/*|frontend/.angular/*)
    echo "Blocked: '$fp' is generated build output. Edit the source instead (backend/src, frontend/src); target/, dist/, node_modules/ and .angular/ are regenerated by the build." >&2
    exit 2
    ;;
esac

exit 0
